### ISSUE TITLE
Not possible to type in "Choices" field while using "Select" block

### ISSUE THREAD

**Issue by michael-hagspiel** [sulu/SuluFormBundle#209] opened 2019-11-28 14:20 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | Specific version or SHA of a commit
| Sulu Version | sulu 2.0.2

#### Actual Behavior

While using a "Select" block it is not possible to type anything into the "Choices" field (see screenshot). This might be only for some languages, as it seems to work in all languages except of german.

![Issue_FormBundle_Select](https://user-images.githubusercontent.com/58299847/69812779-2132f680-11f1-11ea-9c64-67de8b4567a1.png)

#### Expected Behavior

It is possible to type something into the "Choices" field.

**Comment by danrot** [comment] 2019-12-10 08:41
I think that might be related with sulu/sulu#4501, but I couldn't reproduce that issue myself... If I create a new form, add a select field in english, save it and switch to german, I can still enter something into the choices field. Can you give more detailed steps to reproduce?

**Comment by michael-hagspiel** [comment] 2019-12-13 08:23
Steps to reproduce:
1. Create a new form with a block, which is not a Select
2. Save the form and go back to the overview page of all forms
3. Open the form again and change the type of the already made block to Select
4. Now you can't type into the Choices Field of that block

**Comment by alexander-schranz** [comment] 2019-12-19 23:56
Short analyse I think it seem like the problem is that the response of the `options` parameter is `[]` instead of `{}`. When using `<property name="options/choices" type="text_area"/>` in the form.

**Comment by alexander-schranz** [comment] 2020-04-29 10:53
This is fixed by #244

**Closed by alexander-schranz** 2020-04-29 10:53 UTC
Labels: bug
