### ISSUE TITLE
Export data from form to csv

### ISSUE THREAD

**Issue by gauquier** [sulu/SuluFormBundle#152] opened 2018-03-29 10:49 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | 1.0.0
| Sulu Version | 2.0

#### Actual Behavior

When you export data to csv the Multiline Textfield data comes in different cells. Each row from the Multiline Textfield comes in a separate cell.

#### Expected Behavior

The Multiline Textfield data must be visible in one cell. 

#### Steps to Reproduce

![screen shot 2018-03-29 at 12 47 10](https://user-images.githubusercontent.com/22136028/38085101-9a546454-334f-11e8-9591-dd9f9599b167.png)
<img width="483" alt="screen shot 2018-03-29 at 12 48 17" src="https://user-images.githubusercontent.com/22136028/38085102-9a6eabac-334f-11e8-82f1-bff275ab7ffd.png">

**Comment by alexander-schranz** [comment] 2018-03-29 11:51
@gauquier looks for me like you did not set the [enclosure](http://php.net/manual/de/function.str-getcsv.php)  when you did import the csv in your program. Or is the original csv text not surrounded by `"`? SuluFormBundle uses the csv export of sulu which is build ontop of [goodby/csv](https://github.com/goodby/csv).

In open office you can set the enclosure in the import and you see in the preview that they are not longer break into a new column:

![bildschirmfoto 2018-03-29 um 13 41 25](https://user-images.githubusercontent.com/1698337/38087367-1cf9c464-3358-11e8-8048-1a73cafda344.png)

**Comment by gauquier** [comment] 2018-03-29 12:09
It's not when I import but when I export data from the sulu form in the backend to csv. There I already chooses " for the enclosure.
![screen shot 2018-03-29 at 14 06 43](https://user-images.githubusercontent.com/22136028/38087966-75fe830e-335a-11e8-86ac-6306f4a9c1dc.png)

**Comment by alexander-schranz** [comment] 2018-03-29 12:22
@gauquier how does the CSV look? Is the enclosure around it when you open the *RAW*  CSV in for example VIM, Nano, Emacs, .... 
The enclosure you need also set in the program you import it that it handles multiline correctly.

**Comment by gauquier** [comment] 2018-03-29 12:40
This is the sentence I get if I open the csv with Nano: 
^@Hello 
This is a test^@;
<img width="564" alt="screen shot 2018-03-29 at 14 39 19" src="https://user-images.githubusercontent.com/22136028/38089246-08ace480-335f-11e8-81c1-1eef2d333f4b.png">

**Comment by alexander-schranz** [comment] 2018-03-29 13:13
@gauquier hmm strange looks like there is a strange problem in the CSV export of sulu can you check if the ^@  also appears for the `contact` export button in sulu?

**Comment by gauquier** [comment] 2018-03-29 13:25
This is what I get: 
<img width="1258" alt="screen shot 2018-03-29 at 15 23 48" src="https://user-images.githubusercontent.com/22136028/38091260-5038cb6a-3365-11e8-8700-f457af6283a5.png">

**Comment by alexander-schranz** [comment] 2018-03-29 13:36
ok looks the same that it is `^@` instead of `"` can you create an issue in [sulu/sulu](https://github.com/sulu/sulu/issues) for it?

**Comment by gauquier** [comment] 2018-03-29 13:51
@alexander-schranz I will do! Thx for helping.

**Comment by alexander-schranz** [comment] 2018-03-29 14:00
@gauquier Thx I will keep this issue open as a reminder for me.

Related Issue: https://github.com/sulu/sulu/issues/3882

**Comment by alexander-schranz** [comment] 2019-11-29 12:02
Closing this issue as I can not longer reproduce it maybe through libraries updates this is now fixed. Feel free to provide more infos under which circumstances it happens.

**Closed by alexander-schranz** 2019-11-29 12:02 UTC
Labels: bug
